- app/code/Magento/ImportService/Api/Data/SourceInterface.php
- app/code/Magento/ImportService/Model/Source.php
- app/code/Magento/ImportService/README.md
- app/code/Magento/ImportService/composer.json
- app/code/Magento/ImportService/etc/db_schema.xml
- app/code/Magento/ImportService/etc/db_schema_whitelist.json
- composer.json
- composer.lock
This PR fixes Unit and Static tests that were failed:
https://travis-ci.org/magento/async-import/builds/476352134?utm_source=github_status&utm_medium=notification
> Base extension fixes

- app/code/Magento/ImportService/Api/Data/SourceInterface.php
- app/code/Magento/ImportService/Api/Data/SourceUploadResponseInterface.php
- app/code/Magento/ImportService/ImportServiceException.php
- app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
- app/code/Magento/ImportService/Model/Import/Processor/SourceProcessorInterface.php
- app/code/Magento/ImportService/Model/Import/SourceProcessorPool.php
- app/code/Magento/ImportService/Model/Import/SourceTypesValidator.php
- app/code/Magento/ImportService/Model/Import/SourceTypesValidatorInterface.php
- app/code/Magento/ImportService/Model/SourceUpload.php
- app/code/Magento/ImportService/Model/SourceUploadResponse.php
- app/code/Magento/ImportService/Model/SourceUploadResponseFactory.php
- app/code/Magento/ImportService/etc/acl.xml
- app/code/Magento/ImportService/etc/di.xml
Implementation of LocalPathFileProcessor
1. magento/async-import #32: Implement of Local file upload processor
1. Create CSV file and place it at the same server with your Magento installation
2. Using curl or ant rest client create REST request with
**url**:
_http://magento-domain/rest/V1/import/source_
**body**:
`{
"source": {
"import_data": "/shared/httpd/async-import/var/import_test/test.csv",
"import_type": "local_path",
"source_type": "csv"
}
}`
**headers**:
Content-Type: application/json
_Authorization: Bearer <admin_user_token>_
1. Record created in db table _**import_service_source**_
2. File saved to var/import folder with unique id and extension from source_type
Response should be:
`{
"source_id": <record_id>,
"status": "uploaded",
"error": null
}`
> Local path file processor

- app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
- app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
- app/code/Magento/ImportService/Model/Import/SourceProcessorPool.php
- app/code/Magento/ImportService/etc/di.xml
Create Base64 Upload Processor class to process base64 data string and create a temporary file in var directory with proper resource_id.  
Defined constant parameter inputs for Local Path processor and Base64 upload processor. 
1. magento/async-import#34: Implement of Base64 upload processor
1. In postman, use [DOMAIN]/rest/V1/import/source URL to with POST type 
2. Define headers to access the API
3. Use below body content with row (application/json) data
{
"source": {
"import_data": "U0tVLFRpdGxlCiJTS1UgMSIsIlRpdGxlIDEi",
"import_type": "base64_encoded_data",
"source_type": "csv"
}
}
> Create Base64 Upload Processor

- app/code/Magento/ImportService/etc/acl.xml
- app/code/Magento/ImportService/etc/webapi.xml
Changes ACL name. Aligned webapi.xml to acl
magento/magento2#55: Create new ACL rule for ImportService
> ASYNC-IMPORT-55: Create new ACL rule for ImportService

- app/code/Magento/ImportService/Api/ImportRestartOperationInterface.php
- app/code/Magento/ImportService/Model/ImportRestartOperation.php
- app/code/Magento/ImportService/etc/di.xml
- app/code/Magento/ImportService/etc/webapi.xml
Create Repeatable call endpoint and dummy service contract restart import service with serialized data.
1. magento/async-import#47: Create Repeatable call endpoint and dummy ServiceContract
1. In postman, use [DOMAIN]/rest/V1/import/operation-id/:uuid URL with PUT request. For example http://127.0.0.1/async-import/rest/V1/import/operation-id/1914670575
2. Define headers to access the API
3. Use body with data `{ "serialized_data": "" }`
`true/false` (boolean)
> Repeatable call endpoint and dummy ServiceContract

- app/code/Magento/ImportService/Api/ImportRestartOperationInterface.php
Failed tests caused by wrong return type
> Fix returned type

- app/code/Magento/ImportService/Model/Source/Validator/MimeTypeValidator.php
Resolve minor issue with detecting mime type for external URLs as well as issue in detecting mime type with charset.
1. magento/async-import#74: Problem with Mime type validation
URL (POST request): [DOMAIN]/rest/V1/import/source
body: `{ "source": { "import_data": "https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv", "import_type": "external", "source_type": "csv" } }`
Headers: Content-Type: application/json, Authorization: Bearer <admin_user_token>
Response should be:
`{ "source_id": 36, "status": "uploaded", "error": null, "source": { "source_id": 36, "source_type": "csv", "import_type": "external", "status": "uploaded", "import_data": "5c9b09c5565a0.csv", "created_at": "2019-03-27 05:27:33" } }`
> Resolve mimetype validator issue

- app/code/Magento/ImportService/Api/Data/SourceFormatInterface.php
- app/code/Magento/ImportService/Api/Data/SourceFormatMappingInterface.php
- app/code/Magento/ImportService/Api/Data/SourceFormatMappingValueInterface.php
- app/code/Magento/ImportService/Api/Data/SourceInterface.php
- app/code/Magento/ImportService/Api/SourceUploadInterface.php
- app/code/Magento/ImportService/Model/Import/Type/FileSourceType.php
- app/code/Magento/ImportService/Model/Source.php
- app/code/Magento/ImportService/Model/SourceFormat.php
- app/code/Magento/ImportService/Model/SourceFormatMapping.php
- app/code/Magento/ImportService/Model/SourceFormatMappingValue.php
- app/code/Magento/ImportService/Model/SourceUpload.php
- app/code/Magento/ImportService/etc/db_schema.xml
- app/code/Magento/ImportService/etc/db_schema_whitelist.json
- app/code/Magento/ImportService/etc/di.xml
- app/code/Magento/ImportService/etc/webapi.xml
Change source upload endpoint and provide a way to define source type within the request URL. Define new format field to database and store format field object as JSON string in the database table.
1. magento/async-import#75: Change Source Upload endpoints
1.  URL (POST request): [DOMAIN]/rest/V1/import/source/csv
2. Body
```
{
"source": {
"import_data": "var/catalog_product.csv",
"import_type": "local_path",
"format": {
"csv_separator": ",",
"csv_enclosure": "\"",
"csv_delimiter": ",",
"multiple_value_separator": "|",
"mapping": [
{
"source_attribute": "string",
"destination_attribute": "string",
"processing_rules": "string",
"taxonomy": "string",
"values_mapping": [
{
"old_value": "value1",
"new_value": "value2"
}, {
"old_value": "value3",
"new_value": "value4"
}
]
}, { …
```
> Change source endpoint with source-type and add format field to source interface

- app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
- app/code/Magento/ImportService/Model/ResourceModel/Source/Collection.php
- app/code/Magento/ImportService/Model/Source.php
- app/code/Magento/ImportService/Model/Source/Command/GetList.php
- app/code/Magento/ImportService/Model/Source/Command/GetListInterface.php
- app/code/Magento/ImportService/Model/SourceRepository.php
- app/code/Magento/ImportService/etc/di.xml
- app/code/Magento/ImportService/etc/webapi.xml
Create an endpoint which provides source records based on criteria provided with API call. 
1. magento/async-import#86: Get All sources API endpoint
URL (GET request): [DOMAIN]/rest/V1/import/sources?criteria
Headers: Authorization: Bearer <admin_user_token>
**Expected Result:**
```
{
"items": [
{
"entity_id": "1",
"uuid": "7ed24a77-2d72-432d-905c-6d67e4bccf37",
"status": "uploaded",
"source_type": "csv",
"import_type": "local_path",
"import_data": "7ed24a77-2d72-432d-905c-6d67e4bccf37.csv",
"created_at": "2019-04-11 11:08:51",
"format": {
"csv_separator": ",",
"csv_enclosure": "\"",
"csv_delimiter": ",",
"multiple_value_separator": "|",
"mapping": [
{
"source_attribute": "string",
"destination_attribute": "string",
"processing_rules": "string",
"taxonomy": "string",
"values_mapping": [
{ …
```
> All sources endpoint

- app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
- app/code/Magento/ImportService/Model/Source/Command/Get.php
- app/code/Magento/ImportService/Model/Source/Command/GetInterface.php
- app/code/Magento/ImportService/Model/SourceRepository.php
- app/code/Magento/ImportService/etc/di.xml
Implemente the get source object by uuid operation by technical guidelines.
https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html (6.4.2.3)
URL (GET request): [DOMAIN]/rest/V1/import/source/:uuid
Headers: Authorization: Bearer <admin_user_token>
**Expected Result:**
```
{
"uuid": "aa8acffc-6d31-4d30-a937-1b96e73aa96e",
"source_type": "csv",
"import_type": "local_path",
"status": "uploaded",
"import_data": "aa8acffc-6d31-4d30-a937-1b96e73aa96e.csv",
"format": {
"csv_separator": ",",
"csv_enclosure": "\"",
"csv_delimiter": ",",
"multiple_value_separator": "|",
"mapping": [
{
"source_attribute": "string",
"destination_attribute": "string",
"processing_rules": "string",
"taxonomy": "string",
"values_mapping": [
{
"old_value": "value1",
"new_value": "value2"
},
{ …
```
> Implement Get operation by using Technical Guidelines

- app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
- app/code/Magento/ImportService/Model/Source/Command/Save.php
- app/code/Magento/ImportService/Model/Source/Command/SaveInterface.php
- app/code/Magento/ImportService/Model/SourceRepository.php
- app/code/Magento/ImportService/etc/di.xml
Implemente the save source object by uuid operation by technical guidelines.
https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html (6.4.2.3)
1. URL (POST request): [DOMAIN]/rest/V1/import/source/csv
2. 
```
{
"source": {
"import_data": "U0tVLFRpdGxlCiJTS1UgMSIsIlRpdGxlIDEi",
"import_type": "base64_encoded_data",
"format": {
"csv_separator": ",",
"csv_enclosure": "\"",
"csv_delimiter": ",",
"multiple_value_separator": "|",
"mapping": [
{
"source_attribute": "string",
"destination_attribute": "string",
"processing_rules": "string",
"taxonomy": "string",
"values_mapping": [
{
"old_value": "value1",
"new_value": "value2"
}, {
"old_value": "value3",
"new_value": "value4"
}
]
}, {
"source_attribute": "string",
"destination_attribute": "string",
"processing_rules": …
```
> Implement Save operation by using Technical Guidelines

- app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
- app/code/Magento/ImportService/Model/Import/Processor/ExternalFileProcessor.php
- app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
- app/code/Magento/ImportService/Model/Source/Validator/ImportServiceValidator.php
- app/code/Magento/ImportService/Model/Source/Validator/ValidatorInterface.php
Small error handling changes, removed unused variable
> Small error handling changed

- lib/internal/Magento/Framework/Redis/Config.php
- lib/internal/Magento/Framework/Redis/Config/ConfigBuilder.php
- lib/internal/Magento/Framework/Redis/ConfigInterface.php
- lib/internal/Magento/Framework/Redis/ConfigProvider.php
- lib/internal/Magento/Framework/Redis/ConfigProviderInterface.php
- lib/internal/Magento/Framework/Redis/README.md
- lib/internal/Magento/Framework/Redis/RedisConnection.php
- lib/internal/Magento/Framework/Redis/RedisConnectionInterface.php
- lib/internal/Magento/Framework/Redis/RedisStorage.php
- lib/internal/Magento/Framework/Redis/Test/Unit/RedisStorageTest.php
- lib/internal/Magento/Framework/Redis/composer.json
Task [magento/async-import#7](https://github.com/magento/async-import/issues/7)
* Implementation of TaggableKeyValueStorageInterface for Redis storage
> Async import redis framework

- app/code/Magento/ImportService/Api/Data/SourceUploadResponseInterface.php
- app/code/Magento/ImportService/Api/SourceCsvUpdateInterface.php
- app/code/Magento/ImportService/Model/Import/Processor/PersistentSourceProcessor.php
- app/code/Magento/ImportService/Model/SourceCsvUpdate.php
- app/code/Magento/ImportService/Model/SourceUploadResponse.php
To follow ResfFull pattern, I removed Source from Source update/create output. For get source objects have to be used GET calls.
> Remove source from response for more resfull approach

- app/code/Magento/AsynchronousImportCsv/Model/CreateCsvSource.php
- app/code/Magento/AsynchronousImportCsv/Model/CsvFormat.php
- app/code/Magento/AsynchronousImportCsvApi/Api/CreateCsvSourceInterface.php
- app/code/Magento/AsynchronousImportCsvApi/Api/Data/CsvFormatInterface.php
- dev/tests/api-functional/testsuite/Magento/AsynchronousImportCsvApi/CreateCsvSourceTest.php
Align csv_separator and csv_delimiter attributes
Pr for 
#147 
#128
> Make "format" for source uploading not required and Align input params

- app/code/Magento/AsynchronousImportDataConverting/Model/RuleApplyingStrategy/LowercaseString.php
- app/code/Magento/AsynchronousImportDataConverting/etc/di.xml
- dev/tests/api-functional/testsuite/Magento/AsynchronousImportCsvApi/LowercaseStringRuleTest.php
https://github.com/magento/async-import/issues/160
> issues/160: Create "StringToLower" converting rule

- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/Base64EncodedData.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/etc/di.xml
- dev/tests/integration/testsuite/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/Base64EncodedDataTest.php
Base64 retriever returns data as ArrayIterator object, including batches. Batch size param was moved to di.xml.
1. magento/magento2#141: "base64" source data retrieving
1. ...
2. ...
> "base64" source data retrieving #141

- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/Base64EncodedData.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceValidator/Base64Validator.php
Make Base64 validator works only for Base64 source
> Make Base64 validator works only for Base64 source

- app/code/Magento/AsynchronousImportDataExchanging/Exception/AdapterNotFoundException.php
- app/code/Magento/AsynchronousImportDataExchanging/Exception/InvalidReceiverConfigurationException.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/Configuration/Config.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/Configuration/ConfigInterface.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/Configuration/RemoteReceiver.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/DataExchangingAdapter/Api.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/ExchangeAdaptersRegistry.php
- app/code/Magento/AsynchronousImportDataExchanging/etc/di.xml
- app/code/Magento/AsynchronousImportDataExchangingApi/Api/Data/RemoteReceiverInterface.php
- app/code/Magento/AsynchronousImportDataExchangingApi/Api/ExchangeAdapterWithReceiverInterface.php
Configuration added to env.php
`'asynchronous_import' => [
'exchange_adapter' => [
'type' => 'api',
'receiver' => [
'integration_token' => '5427ukhllllwpo23po',
'base_url' => 'https://some-receiving-endpoint'
]
]
]`
> Import Prototyping: Receive Adapter configuration

- app/code/Magento/AsynchronousImportDataConverting/Model/ApplyConvertingRules.php
1. magento/magento2#<issue_number>: Issue title
1. ...
2. ...
> #185 - Apply sorting for Converting Rules

- app/code/Magento/AsynchronousImportDataExchanging/Model/Configuration/Config.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/Configuration/ConfigInterface.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/DataExchangingAdapter/Api.php
- app/code/Magento/AsynchronousImportDataExchanging/Model/ExchangeAdaptersRegistry.php
- app/code/Magento/AsynchronousImportDataExchangingApi/Api/MiddlewareExchangeAdapterInterface.php
Edited env.php configuration may look similar to
`'asynchronous_import' => [
'exchange_adapter' => 'api',
'api' => [
'parameters' => [
'integration_token' => '5427ukhllllwpo23po',
'base_url' => 'https://some-receiving-endpoint'
]
]
]`
> Restructure env.php setup

- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/LocalFile.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/LocalFile/FileResolver.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceDataRetrievingStrategy/RemoteHttp.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceValidator/LocalFileValidator.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/Model/SourceValidator/RemoteHttpValidator.php
- app/code/Magento/AsynchronousImportSourceDataRetrieving/etc/di.xml
- app/code/Magento/AsynchronousImportSourceDataUpload/Model/SourceDataUpload.php
- app/code/Magento/AsynchronousImportSourceDataUpload/Model/SourceDataUploadResult.php
- app/code/Magento/AsynchronousImportSourceDataUpload/composer.json
- app/code/Magento/AsynchronousImportSourceDataUpload/etc/di.xml
Created logic retrieving source data from local file and remote http source. Created validation files. Moved logic identifying uploading files path from AsynchronousImportSourceDataUpload to AsynchronousImportSourceDataRetrieving module.
1. magento/magento2#<issue_number>: Issue title
1. ...
2. ...
> AsynchronousImportSourceDataRetrieving module "local_file" and "remote_http" source data fetching strategies

- app/code/Magento/AsynchronousImportCsv/Model/DataParser.php
- app/code/Magento/AsynchronousImportCsv/Model/StartImport.php
Use format paramaters for parsing CSV data
> add using parameters for CSV data
